Default:
    Baseline: tizen-3.0
    FileSystem: ext4
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: America/Los_Angeles
    RootPass: tizen
    DefaultUser: tizen
    DefaultUserPass: tizen
    PartSize: 3200
    BootloaderOptions: ""


BASE:
    Bootloader: True
    BootloaderAppend: "vga=current quiet splash"
    BootloaderTimeout: 1
    SaveRepos: True
    StartX: False
    Architecture: x86_64
    Desktop: None
    Mic2Options: -f liveusb --copy-kernel
    Groups:
        - Base System
    Repos:
        - base
PC:
    Bootloader: True
    BootloaderAppend: "vga=current quiet splash"
    BootloaderTimeout: 1
    SaveRepos: True
    StartX: False
    Mic2Options: -f liveusb --copy-kernel
    Architecture: x86_64
    Desktop: None
    Groups:
        - Base System
    Repos:
        - base
        - pc
