Name: Base Enlightenment Desktop
Schedule: "*"
Active: True
Platform: BASE
FileName: enlightenment
Kernel: kernel-adaptation-pc
Architecture: x86_64
Desktop: None
PostScripts:
    - workarounds
    - base-general
    - base-e17-default
Groups:
    - Base System
    - X11
    - SLP Fonts
    - Enlightenment
    - Development
    - Applications
