Description: Base System
Name: base
Packages:
- dracut
- openssh
- e2fsprogs
- util-linux
- grep
- connman
- rfkill
- kmod-compat
- kmod
- kernel-adaptation-pc
- tzdata
- setup
- filesystem
- systemd
- user-session-units
- bash
- coreutils
- rpm
- vim
- tar
- gzip
- curl
- tizen-release
- zypper
- procps
- psmisc
- net-tools
- parted
- kbd
- glibc-locale
- linux-firmware
- pciutils
- wpa_supplicant
- rsync
- update-desktop-files
- desktop-file-utils
Summary: Base System
