Description: Base System
Name: base
Packages:
- openssh
- e2fsprogs
- util-linux
- grep
- kmod-compat
- kmod
- tzdata
- pwdutils
- pam
- setup
- filesystem
- systemd
- bash
- coreutils
- rpm
- tar
- gzip
- curl
- tizen-release
- zypper
- procps
- psmisc
- net-tools
- kbd
- glibc-locale
- pciutils
- connman
Summary: Base System
