Description: IVI Applications
Name: ivi-applications
Packages:
- GhostCluster
- Settings
- MediaPlayer
- ca-certificates
- ca-certificates-mozilla
- festival
- ico-vic-amb-plugin
- pocketsphinx
- saythis
- settingsd
- sphinxbase
- webkit2-efl-test
- weston-ivi
Summary: IVI Applications
