Summary: IVI Applications
Description: IVI Applications
Name: ivi-applications
Packages:
- app-installers
- tpk-backend
- wgt-backend
- smartdevicelink
- org.tizen.homescreen
- org.tizen.ode
- org.tizen.dpm-syspopup
- org.tizen.bootsplash
- org.tizen.screen-reader
