Description: IVI Applications
Name: ivi-applications
Packages:
- festival
- GhostCluster
- MediaPlayer
- pocketsphinx
- sphinxbase
- syncevolution
- syncevolution-devel        
- syncevolution-ebook        
- syncevolution-ecal        
- syncevolution-pbap         
- syncevolution-phone-config 
- syncevolution-synccompare 
- webkit2-efl-test
Summary: IVI Applications
