Description: IVI Applications
Name: ivi-applications
Packages:
- GhostCluster
- ca-certificates
- ca-certificates-mozilla
- festival
- pocketsphinx
- saythis
- settingsd
- sphinxbase
Summary: IVI Applications
