Description: IVI Applications
Name: ivi-applications
Packages:
- GhostCluster
- Settings
- MediaPlayer
- ca-certificates
- ca-certificates-mozilla
- evolution-data-server
- festival
- pocketsphinx
- saythis
- sphinxbase
- webkit2-efl-test
Summary: IVI Applications

#syncevolution
#syncevolution-ebook        
#syncevolution-ecal        
#syncevolution-pbap         
#syncevolution-phone-config 
#syncevolution-synccompare 

