Description: IVI Applications
Name: ivi-applications
Packages:
- evolution-data-server
- festival
- GhostCluster
- MediaPlayer
- pocketsphinx
- Settings
- sphinxbase
- webkit2-efl-test
Summary: IVI Applications

#syncevolution
#syncevolution-devel        
#syncevolution-ebook        
#syncevolution-ecal        
#syncevolution-pbap         
#syncevolution-phone-config 
#syncevolution-synccompare 

